apiVersion: v1
kind: PersistentVolume
metadata:
  name: week1-sts1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""  
  hostPath:
    path: /tmp
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: week1-sts2
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""  
  hostPath:
    path: /tmp
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: week1-sts3
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""  
  hostPath:
    path: /tmp
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: week1-sts
  namespace: default
spec:
  selector:
    matchLabels:
      app: week1-sts
  serviceName: "week1-sts"
  replicas: 3
  template:
    metadata:
      labels:
        app: week1-sts
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: main
        image: nginx:1.21
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /tmp
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ""
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: week1-sts
  labels:
    app: week1-sts
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: week1-sts